#cloud-config
runcmd:
  - sudo apt update
  - sudo apt install -y nodejs
  - sudo apt install -y npm
  - mkdir -p /home/azureuser/project
  - git clone https://github.com/rutvikmhatre7/node-express-hello-world.git /home/azureuser/project
  - mv /home/azureuser/startup.sh /home/azureuser/project/
  - bash /home/azureuser/project/startup.sh

write_files:
- content: |
    #!/bin/bash
    set -x 
    npm install
    npm start&
  
  path: /home/azureuser/startup.sh
  permission: '0644'
  owner: root:root
